version: '3'

services:
  nginx:
    container_name: invited_nginx
    build:
      context: development/nginx
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/invited
    ports:
      - "8888:80"
    depends_on:
      - php-fpm
  php-fpm:
    container_name: invited_php-fpm
    build:
      context: development/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/invited
    depends_on:
      - database
  node:
    container_name: invited_node
    build:
      context: development/node
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/invited
    tty: true
    ports:
      - "3331:3331"
  database:
    container_name: invited_database
    image: postgres:15.1-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: invited
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: invited
    ports:
      - "5434:5432"
#  redis:
#    container_name: invited_redis
#    image: redis:6.0-alpine
#    volumes:
#      - redis:/data
#    ports:
#      - "6378:6379"
#    command: redis-server --requirepass secret

volumes:
  database:
#  redis: